name: pr

on:
  pull_request:
    branches: [ "**" ]

env:
  UV_VERSION: "0.6.5"
  PYTHONPATH: "src"
  PYTHONUNBUFFERED: 1
  UV_CACHE_DIR: /tmp/.uv-cache

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Read Python version from pyproject.toml
        id: python-version
        run: |
          echo "version=$(grep '^requires-python = ' pyproject.toml | cut -d'"' -f2 | cut -d'>=' -f2)" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.python-version.outputs.version }}

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/${{ env.UV_VERSION }}/install.sh | sh

      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}

      - name: Install dependencies
        run: uv sync --all-extras --dev --frozen

      - name: Test with pytest
        run: uv run pytest tests --cov=pyfinquant

      - name: Minimize uv cache
        run: uv cache prune --ci 
